### ISSUE TITLE
Way to change folder in which files go?

### ISSUE THREAD

**Issue by MaiRiosIPla** [bariseksi/iphone-shortcuts-media-transfer#2]
Hi, I was wondering whether there is a way to have the .exe in one folder but the files in the downloads folder (without modifying the code).

**Comment by bariseksi** [comment]
you need to modify the code in order to this. Its not that hard actually.

in the code you can do something like

fileName = "Downloads\\" + fileName + "." + fileExtention;

**Comment by MaiRiosIPla** [comment]
Thanks, I'll try it. I actually found another way: Creating a bat file that goes to downloads and runs the script (which is in another folder):

@echo off
cd C:\ (path) \Downloads
start "" "C:\ (another path) \ShortcutsListener.exe"
